name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  codspeed:
    name: Run benchmarks
    runs-on: codspeed-macro
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s) for simulation
        run: cargo codspeed build -m simulation

      - name: Build the benchmark target(s) for walltime
        run: cargo codspeed build -m walltime

      - name: Run the benchmarks(simulation)
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: cargo codspeed run
      - name: Run the benchmarks(walltime)
        uses: CodSpeedHQ/action@v4
        with:
          mode: walltime
          run: cargo codspeed run
